title: Donal Hill # your name (or website title) here
logo: "/images/donal_final3.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Using Data Science and Machine Learning to innovate | Entrepreneur | CERN high energy physicist | University of Oxford PhD
  <br><br>
  Welcome to my GitHub data science portfolio. This page hosts some examples of my data analysis, machine learning, and public engagement work.
  <br><br>
  <a href="https://www.linkedin.com/in/donalhill/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
